### ISSUE TITLE
8월 30일 버그 리포팅

### ISSUE THREAD

**Issue by starkim06** [wbluke/miniprojects-2019#209]
- [x] 하트 위에 살짝 위에 누르면 새로고침되는 문제
- [x] 로그인 잘못했을 때 오류 관련 메시지 표시
- [x] 브라우저 콘솔창에 로그 찍히는거 수정
- [x] 회원가입 여부 메시지 표시
- [x] 댓글 작성 도중에 해당 글을 작성자가 삭제하면 의도치 않은 결과 발생
  - [ ] alert로 [Object object]가 발생함
- [x] 이미지 파일만 업로드 가능하도록 수정
- [x] 메인페이지의 댓글에는 html 형식이 적용 가능하고 해당 게시글로 들어가면 적용 안 되는 문제 수정
- [x] 게시글에서 유저 이름을 누르면 해당 유저 페이지로 이동
- [x] 다른 사람 게시글 삭제시 undefined 출력 문제 수정
