### ISSUE TITLE
[3주차] 프론트 코드 리뷰 

### ISSUE THREAD

**Issue by wbluke** [wbluke/miniprojects-2019#220]
- [x] url에 문자열 리터럴 적용하기

- [x] boolean 값 if 문 확인!
- [x] 재할당 없는 변수는 let 대신 const 사용하기
- [x] classList 연속할당 적용하기

- [ ] cdn 라이브러리 재사용하기
- [x] tag.js 파일에서 구현된 Api 객체처럼 ajax 통신하는 역할을 담당하는 객체를 따로 만들고, js파일로 분리한다음 관리되면 더 좋을 것 같아요 :) => ajax 통신 js 파일 분리하기
- [x] ddabongService 별도 js파일로 분리하기
- [x] commentService 별도 js파일로 분리하기
